### PR TITLE
Solves build error due to to_h not working in Ruby 2.0

### PR DESCRIPTION
**Pull request by lokeshh**

### CODE REVIEW

**Comment by lokeshh** [comment]
Build should be error free now. I added backports which was in why `to_h` was working in Daru in Ruby 2.0 but still not sure why do I have to explicitly include backports.

**Comment by v0dro** [comment]
We'll be dropping 1.9.3 support so whatever code relates to that should not make it's way into this PR.

**Comment by v0dro** [comment]
Also, your build in failing.

**Comment by lokeshh** [comment]
The build is failing due to some specs failing. This is a different issue I
think.

This fix solves the issue but have to dug deeper to know the reason why
things are working the way they are. Then I will come up with a more
reliable fix. This fix is for just the case you need an immediate solution.

**Comment by lokeshh** [comment]
I know what's the causing the issue now.

The problem is with Daru. The reason why the tests in Daru are passing even through Ruby 2.0 doesn't support `to_h` is because at development time there is a a gem 'backports' which gets added which provides `to_h` for Enumerable. If I just install Daru on Ruby 2.0, then it won't work if I don't have backports pre installed. backports comes with nmatrix as it's dependency. That's why Daru was working in statsample because statsample has nmatrix as it's dependency but statsample-glm. 

The fix would be include backports in Daru and it will fix everything. Closing this pull request and instead making changes in Daru.

**Pull request closed without merging**
