### PR TITLE
drop 1.9 support and add 2.3 and JRuby

### LINKED ISSUE #22: Drop 1.9.3 support and update Travis with latest rubies
Rubies should ideally include JRuby too.

### PR DESCRIPTION
**Pull request by lokeshh**
Fixes #22

### CODE REVIEW

**Comment by lokeshh** [comment]
Any pointers to how to include JRuby?

**Comment by v0dro** [comment]
Check the travis docs.

**Comment by agisga** [comment]
Regarding JRuby. I was thinking about migrating the computational algorithms of statsample-glm from Matrix to NMatrix, for better performance. At the same time I could remove some computational bottlenecks (for example matrix inverses are taken all over the place, where a linear solver would be much more efficient).

But NMatrix is currently not compatible with JRuby, right? What do you think?

**Comment by v0dro** [comment]
We could have an alternate implementation for normal Ruby and MRI specific code.

Have you seen the distribution gem? It's full of this kind of stuff. Here's an example: https://github.com/SciRuby/distribution/tree/master/lib/distribution/binomial

**Comment by agisga** [comment]
I see. Thanks!

**Comment by v0dro** [comment]
Just make sure you activate the gem, since we can't include it as a runtime dependency in the gemspec (bundler does not allow conditional dependencies).

Here's an example that I put in the rb-gsl gem. Works fine. https://github.com/SciRuby/rb-gsl/blob/master/ext/gsl_native/extconf.rb#L70

**Comment by lokeshh** [comment]
Got this error with JRuby:

```ruby
SyntaxError: /home/travis/.rvm/gems/jruby-src-1.7.19/gems/daru-0.1.3.1/lib/daru/dataframe.rb:333: syntax error, unexpected tPOW

              @data << Daru::Vector.new(source[name].dup, name: set_name(name), **meta_opt, index: @index)

                                                                                  ^

          require at org/jruby/RubyKernel.java:1071
```

I guess we have to make Daru compatible with JRuby first.

**Comment by v0dro** [comment]
Ok works. Keep this on hold until that happens. We'll release the new daru minor version with JRuby compatibility.

**Comment by v0dro** [comment]
@lokeshh can you create a separate PR with only dropped 1.9.3 support and added 2.3 support? JRuby will take time.

**Comment by lokeshh** [comment]
Here it is https://github.com/SciRuby/statsample-glm/pull/29.

I am closing this PR for now.

**Pull request closed without merging**
